### ISSUE TITLE
Change DNS for jncc.gov.uk and link to the new webserver

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/jncc-website#60] opened 2019-06-26 13:14 UTC
on the day before go live

Change DNS for jncc.gov.uk and link to the new webserver
Set up https: for jncc.gov.uk on new server

**Comment by mattdebont** [comment] 2019-07-01 12:44
duplicate of #58 ?

**Closed** 2019-07-05 15:20 UTC
