### ISSUE TITLE
Create AWS accounts for search access

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/jncc-website#24] opened 2018-12-12 14:56 UTC
`jncc-website-live-search-reader` and `jncc-website-live-search-writer`

**Comment by mattdebont** [comment] 2018-12-13 09:51
duplicate of dev/#181

**Comment by PeteMontgomery** [comment] 2018-12-19 10:40
Accounts for ES read and Lambda / API write created.

**Closed** 2018-12-21 16:48 UTC
